[package]
name = "j2534"
version = "0.3.4"
authors = ["Altenius <jacobjm18@gmail.com>"]
keywords = ["cars", "tuning", "passthru"]
categories = ["external-ffi-bindings", "hardware-support"]
description = "PassThru (SAE J2534) bindings."
documentation = "https://docs.rs/j2534"
repository = "https://github.com/altenius/j2534-rs"
license = "MIT"
readme = "README.md"
edition = "2018"

[package.metadata.docs.rs]
all-features = true
default-target = "i686-pc-windows-msvc"

[dependencies]
bitflags = "2.9"
cfg-if = "1.0.1"
libloading = "0.8"
thiserror = "2.0"

[target.'cfg(windows)'.dependencies]
winreg = "0.8"
pe-parser = "0.7.0"
